# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.cache/wt [current_project]
set_property parent.project_path C:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  C:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.srcs/sources_1/new/defines.vh
  C:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.srcs/sources_1/new/opcode.vh
}
read_verilog -library xil_defaultlib {
  C:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.srcs/sources_1/new/cache.v
  C:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.srcs/sources_1/new/ctrl.v
  C:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.srcs/sources_1/new/ex.v
  C:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.srcs/sources_1/new/fifo.v
  C:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.srcs/sources_1/new/id.v
  C:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.srcs/sources_1/new/mem.v
  C:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.srcs/sources_1/new/midbuf.v
  C:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.srcs/sources_1/new/pc_reg.v
  C:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.srcs/sources_1/new/regfile.v
  C:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.srcs/sources_1/new/risc32i.v
  C:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.srcs/sources_1/new/uart_comm.v
  C:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.srcs/sources_1/new/sopc.v
}
read_ip -quiet c:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.srcs/constrs_1/new/cons.xdc
set_property used_in_implementation false [get_files C:/Users/99486/Desktop/architecture/risc-v/risc-v/risc-v.srcs/constrs_1/new/cons.xdc]


synth_design -top sopc -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef sopc.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file sopc_utilization_synth.rpt -pb sopc_tb_utilization_synth.pb"
